// Generated by tools/parser.py --code. Edit freely.
// Player -> role mapping (first-seen order inside the window):
//   1082FBC5  Mr Ride                   -> PartyRole.MainTank
//   10696ED8  Cherry Moon               -> PartyRole.OffTank
//   108C0704  Kal Mor'kal               -> PartyRole.RegenHealer
//   1070BF7F  Fae Luci                  -> PartyRole.ShieldHealer
//   1064B106  Kitsune Cassie            -> PartyRole.MeleeDpsA
//   1077591B  Pri Eon                   -> PartyRole.MeleeDpsB
//   10782F7D  Rivian Aaaah              -> PartyRole.PhysRangedDps
//   10890EEA  Aurora Fallingstar        -> PartyRole.CasterDps
// Suppressed 261|Change keys (state-sync churn ù no C# emission):
//   CurrentMP, Heading, MaxHP, NPCTargetID, PCTargetID, PosX, PosY, PosZ

using System;
using System.Collections.Generic;
using System.Numerics;
using AnoMech.Core;
using AnoMech.Core.Map;
using AnoMech.Core.SimObjects;
using static AnoMech.Scenarios.Top.TopConstants;

namespace AnoMech.Scenarios.Top.P5Omega;

public sealed class TopP5OmegaScenario : IScenario
{
    public string Name => "TOP P5 Omega";
    public TargetInstance? TargetInstance { get; } = new(
        TerritoryId: 1122,
        Origin: new Vector3(100.000f, 0f, 100.000f),
        PlayerPosition: new Vector3(100.000f, 0f, 116.000f),
        WeatherId: 174);
    public IReadOnlyList<ScenarioOriginOverride> OriginOverrides { get; } = [
        new(TerritoryId: 801, X: 100.000f, Z: 100.000f),
    ];
    public IReadOnlyList<uint> HiddenBaseIds { get; } = [];
    public IReadOnlyList<Waymark> Waymarks { get; } = TopUtils.TopWaymarks;
    public ushort Bgm => BgmId.TopP5;

    private SimWorld world = null!;
    private SimParty party = null!;
    private TopUtils topUtils = null!;
    
    TopP5OmegaState state = null!;
    public void DrawSettings() => settingsWindow.Draw();
    private readonly TopP5OmegaSettingsWindow settingsWindow = new();

    public void Run(SimWorld worldParam)
    {
        world = worldParam;
        party = worldParam.Party;
        state = new TopP5OmegaState(world.Party, settingsWindow.Overrides);
        new TopP5OmegaAi(state).Run(world);

        topUtils = new TopUtils(world);

        world.EnforceArenaBoundary(Geometry.ArenaRadius);
        world.Events.Add(1f, () => topUtils.InitTopArena());
        
        Run_Omega_M_4000A63C();
        Run_Omega_F_4000A72A();
        Run_Omega_4000A72E();
        Run_Omega_4000A72F();
        Run_Omega_4000A40B_1();
        Run_Omega_F_4000A40B_2();
        Run_Omega_4000A409_1();
        Run_InstanceEvents();
        Run_OtherDebuffs();
    }

    private void Run_InstanceEvents()
    {
        world.Events.Add(30.96f, () => world.Map.DirectorUpdate(0x80000004U, 0x1517U));
    }

    private void Run_OtherDebuffs()
    {
        world.Events.Add(0.5f, () =>
        {
            party.ForEachActive(member => member.AddStatus(StatusId.QuickeningDynamis, stacks: 1));
            state.DoubleDynamicTargets.ForEach(member => member.AddStatus(StatusId.QuickeningDynamis, stacks: 1));
        });
        world.Events.Add(9.21f, () =>
        {
            ushort[] statuses1 = [StatusId.HelloNearWorld, StatusId.HelloDistantWorld, StatusId.HelloNearWorld, StatusId.HelloDistantWorld];
            float[] durations = [32f, 32f, 50f, 50f];
            ushort[] statuses2 = [StatusId.FirstInLine, StatusId.FirstInLine, StatusId.SecondInLine, StatusId.SecondInLine];
            state.HelloWorldTargets.ForEach((i, member) =>
            {
               member.AddStatus(statuses1[i], durations[i]);
               member.AddStatus(statuses2[i]);
            });
        });
        world.Events.Add(41.16f, () =>
        {
            state.HelloWorldTargets.Get(0)?.RemoveStatus(StatusId.FirstInLine);
            state.HelloWorldTargets.Get(1)?.RemoveStatus(StatusId.FirstInLine);
        });
        world.Events.Add(59.18f, () =>
        {
            state.HelloWorldTargets.Get(2)?.RemoveStatus(StatusId.SecondInLine);
            state.HelloWorldTargets.Get(3)?.RemoveStatus(StatusId.SecondInLine);
        });
    }

    public void Tick(float delta, float elapsed)
    {
        topUtils.CheckHelloWorldDeath();
    }

    private void Run_Omega_M_4000A63C()
    {
        SimEnemy? omega_M_4000A63C = null;
        world.Events.Add(0, () => omega_M_4000A63C = world.SpawnEnemy(new EnemySpawnConfig(InitialModeAttributeFlags: 0x10, BNpcBaseId: BNpcBaseId.OmegaFDynamis, NameId: BNpcNameId.OmegaFDynamis, Level: 90, Targetable: true, EnemyList: EnemyListMode.Always, IsVisible: true, Placement: new Placement(new Vector3(-000f, -0.000f, 0.000f), MathF.PI))));
        world.Events.Add(1.15f, () => omega_M_4000A63C?.Cast(ActionId.RunMiOmegaVersion, targetLocation: new Vector3(-0.008f, -0.015f, -0.008f), castSeconds: 4.700f, targetId: omega_M_4000A63C?.GameObjectId));
        world.Events.Add(6f, () => omega_M_4000A63C?.Follow(party.Get(PartyRole.MainTank)));
        world.Events.Add(6.81f, () => omega_M_4000A63C?.Cast(ActionId.Unknown7c02, castSeconds: 0f, targetId: party.Get(PartyRole.MainTank)?.GameObjectId));
        world.Events.Add(9.83f, () => omega_M_4000A63C?.Cast(ActionId.Unknown7c02, castSeconds: 0f, targetId: party.Get(PartyRole.MainTank)?.GameObjectId));
        world.Events.Add(12.85f, () => omega_M_4000A63C?.Cast(ActionId.Unknown7c02, castSeconds: 0f, targetId: party.Get(PartyRole.MainTank)?.GameObjectId));
        world.Events.Add(15.88f, () => omega_M_4000A63C?.Cast(ActionId.Unknown7c02, castSeconds: 0f, targetId: party.Get(PartyRole.MainTank)?.GameObjectId));
        world.Events.Add(18.90f, () => omega_M_4000A63C?.Cast(ActionId.Unknown7c02, castSeconds: 0f, targetId: party.Get(PartyRole.MainTank)?.GameObjectId));
        world.Events.Add(21.93f, () => omega_M_4000A63C?.Cast(ActionId.Unknown7c02, castSeconds: 0f, targetId: party.Get(PartyRole.MainTank)?.GameObjectId));
        world.Events.Add(24.96f, () => omega_M_4000A63C?.Cast(ActionId.Unknown7c02, castSeconds: 0f, targetId: party.Get(PartyRole.MainTank)?.GameObjectId));
        world.Events.Add(27.98f, () => omega_M_4000A63C?.Cast(ActionId.Unknown7c02, castSeconds: 0f, targetId: party.Get(PartyRole.MainTank)?.GameObjectId));
        world.Events.Add(31.01f, () => omega_M_4000A63C?.Cast(ActionId.Unknown7c02, castSeconds: 0f, targetId: party.Get(PartyRole.MainTank)?.GameObjectId));
        world.Events.Add(31.54f, () => omega_M_4000A63C?.Follow());
        world.Events.Add(31.54f, () => omega_M_4000A63C?.SetTargetable(false));
        world.Events.Add(31.63f, () => omega_M_4000A63C?.PlayActionTimeline(TimelineId.WarpOut));
        world.Events.Add(59.40f, () => omega_M_4000A63C?.SetPosition(new Placement(new Vector3(0.000f, 0.000f, 0.000f), 3.142f)));
        world.Events.Add(59.49f, () => omega_M_4000A63C?.PlayActionTimeline(TimelineId.Spawn));
        // world.Events.Add(60.52f, () => omega_M_4000A63C?.SetVisible(true));
        world.Events.Add(63.59f, () => omega_M_4000A63C?.SetTargetable(true));
    }

    private void Run_Omega_F_4000A72A()
    {
        uint[] bNpcBaseIds = [BNpcBaseId.OmegaFDynamis, BNpcBaseId.OmegaMDynamis, BNpcBaseId.OmegaFDynamis, BNpcBaseId.OmegaMDynamis];
        uint[] bNpcNameIds = [BNpcNameId.OmegaFDynamis, BNpcNameId.OmegaMDynamis, BNpcNameId.OmegaFDynamis, BNpcNameId.OmegaMDynamis];
        float[] timeOffset = [-3.95f, -3.95f, 0f, 0f];
        for (var i = 0; i < 4; i++)
        {
            var baseId = bNpcBaseIds[i];
            var nameId = bNpcNameIds[i];
            var attack = state.OmegaAttacks[i];
            var direction = state.AttackDirections[i];
            var offset = timeOffset[i];
            SimEnemy? omega_F_4000A72A = null;
            world.Events.Add(1.39f, () => omega_F_4000A72A = world.SpawnEnemy(new EnemySpawnConfig(InitialModeAttributeFlags: attack.AttributeFlags, BNpcBaseId: baseId, NameId: nameId, Level: 90, Targetable: false, EnemyList: EnemyListMode.OnlyWhenVisible, IsVisible: false, Placement: direction.Apply(new Placement(new Vector3(0,  0, -9.8f), 0)))));
            world.Events.Add(15.30f + offset, () => omega_F_4000A72A?.PlayActionTimeline(TimelineId.Spawn));
            world.Events.Add(15.39f + offset, () => omega_F_4000A72A?.SetVisible(true));
            world.Events.Add(26.96f + offset, () => omega_F_4000A72A?.Cast(attack.ActionId, castSeconds: 1.2f, omenDelay: Duration.OmegaAttackOmenDelay));
            world.Events.Add(28.16f + offset, () => topUtils.ResolveOmegaAttack(omega_F_4000A72A, attack.ActionId));
            world.Events.Add(31.59f + offset, () => omega_F_4000A72A?.PlayActionTimeline(TimelineId.WarpOut));
            world.Events.Add(33.83f + offset, () => omega_F_4000A72A?.Despawn());
        }
    }



    private void Run_Omega_4000A72E()
    {
        SimEnemy? omega_4000A72E = null;
        SimTether? tether1 = null;
        SimTether? tether2 = null;
        var placement =state.BettleSpawnDirection.Apply(new Placement(new Vector3(0.000f, 0.000f, -20.000f), 0));
        world.Events.Add(1.39f, () => omega_4000A72E = world.SpawnEnemy(new EnemySpawnConfig(BNpcBaseId: BNpcBaseId.BeetleHelper, NameId: BNpcNameId.OmegaBeetle, Level: 90, Targetable: false, EnemyList: EnemyListMode.OnlyWhenVisible, IsVisible: false, Placement: placement)));
        world.Events.Add(41.29f, () => omega_4000A72E?.PlayActionTimeline(TimelineId.Spawn));
        world.Events.Add(41.29f, () => omega_4000A72E?.SetVisible(true));
        world.Events.Add(45.35f, () => tether1 = world.TetherPassable(state.InitialTetherTargets.Get(0), omega_4000A72E, TetherId.PassableTether));
        world.Events.Add(45.35f, () => tether2 = world.TetherPassable(state.InitialTetherTargets.Get(1), omega_4000A72E, TetherId.PassableTether));
        world.Events.Add(45.43f, () => omega_4000A72E?.Cast(ActionId.Blaster));
        world.Events.Add(57.53f, () => omega_4000A72E?.Cast(ActionId.BlasterEffect, castSeconds: 0f, targetId: omega_4000A72E?.GameObjectId));
        world.Events.Add(60.65f, () => omega_4000A72E?.PlayActionTimeline(TimelineId.WarpOut));
        // world.Events.Add(61.44f, () => omega_4000A72E?.SetVisible(false));
        world.Events.Add(63.07f, () => omega_4000A72E?.Despawn());
        
        for (int index = 0; index < 2; index++)
        {
            SimEnemy? omega_4000A40C_3 = null;
            var i = index;
            world.Events.Add(57.50f, () => omega_4000A40C_3 = world.SpawnEnemy(new EnemySpawnConfig(BNpcBaseId: BNpcBaseId.OmegaHelper, NameId: BNpcNameId.OmegaBeetle, Level: 1, Targetable: false, EnemyList: EnemyListMode.Never, IsVisible: false, Placement: placement)));
            world.Events.Add(57.58f, () =>
            {
                var tether = i == 0 ? tether1 : tether2;
                if (tether?.A == null) return;
                omega_4000A40C_3?.Cast(ActionId.BlasterAoe, castSeconds: 0f, targetId: tether.A.GameObjectId);
                ResolveBlaster(tether.A);
                tether.Despawn();
            });
        }
    }

    private void ResolveBlaster(SimCharacter tetherA)
    {
        if (tetherA is not SimPartySlot slot || !slot.IsAlive) return;
        var lethal = topUtils.IsDamageLethal(slot, ruin: true);
        Plugin.Log.Info($"Hit: {slot.Role} by Blaster ({(lethal ? "lethal" : "non-lethal")})");
        if (lethal)
        {
            slot.Die("Blaster");
            return;
        }
        slot.AddStatus(StatusId.MagicVulnerabilityUp, 4.960f);
        slot.AddStatus(StatusId.TwiceComeRuin, 10.960f);
        slot.AddStatus(StatusId.HPPenalty, 3.000f);
    }

    private void Run_Omega_4000A72F()
    {
        SimEnemy? omega_4000A72F = null;
        var waveCannonId = state.FirstWaveCannonFront ? ActionId.OmegaDiffuseWaveCannonFront : ActionId.OmegaDiffuseWaveCannonSides;
        var repCannonId = state.FirstWaveCannonFront ? ActionId.OmegaDiffuseWaveCannonRepeatSides : ActionId.OmegaDiffuseWaveCannonRepeatFront;
        world.Events.Add(1.39f, () => omega_4000A72F = world.SpawnEnemy(new EnemySpawnConfig(BNpcBaseId: BNpcBaseId.FinalHelper, NameId: BNpcNameId.OmegaFinal, Level: 90, Targetable: false, EnemyList: EnemyListMode.OnlyWhenVisible, IsVisible: false, Placement: new Placement(new Vector3(0.000f, -0.000f, 0.000f), 3.140f))));
        world.Events.Add(11.34f, () => omega_4000A72F?.PlayActionTimeline(TimelineId.Spawn));
        world.Events.Add(11.44f, () => omega_4000A72F?.SetVisible(true));
        world.Events.Add(15.48f, () => omega_4000A72F?.Cast(waveCannonId));
        world.Events.Add(27.54f, () => omega_4000A72F?.Cast(repCannonId));
        world.Events.Add(31.68f, () => omega_4000A72F?.Cast(state.MonitorSide.ActionId));
        world.Events.Add(44.81f, () => omega_4000A72F?.PlayActionTimeline(TimelineId.WarpOut));
        world.Events.Add(47.13f, () => omega_4000A72F?.Despawn());
    }

    private void Run_Omega_4000A40B_1()
    {
        float[] timeOffset = [0f, 0f, 4f, 4f];
        float[] orientations = state.FirstWaveCannonFront
            ? [0, MathF.PI, MathF.PI / 2, -MathF.PI / 2]
            : [MathF.PI / 2, -MathF.PI / 2, 0, MathF.PI];
        
        for(var i = 0; i < 4; i++)
        {
            var offset = timeOffset[i];
            var orientation = orientations[i];
            SimEnemy? omega_4000A40B_1 = null;
            world.Events.Add(23.56f + offset, () => omega_4000A40B_1 = world.SpawnEnemy(new EnemySpawnConfig(BNpcBaseId: BNpcBaseId.OmegaHelper, NameId: BNpcNameId.OmegaFinal, Level: 1, Targetable: false, EnemyList: EnemyListMode.Never, IsVisible: false, Placement: new Placement(new Vector3(0.000f, -0.000f, 0.000f), orientation))));
            world.Events.Add(23.58f + offset, () => omega_4000A40B_1?.Cast(ActionId.OmegaDiffuseWaveCannonAOE, castSeconds: 0.700f));
            world.Events.Add(24.28f + offset, () => ResolveDiffuseWaveCannon(omega_4000A40B_1));
        }
    }

    private void ResolveDiffuseWaveCannon(SimEnemy? omega4000A40B1)
    {
        if (omega4000A40B1 is not { IsAlive: true } unit) return;
        // 120° cone (60° half-angle) per the OmegaDiffuseWaveCannonAOE comment in
        // TopConstants. The Action sheet doesn't carry cone width, so override.
        foreach (var hit in party.Find.InsideActionAoe(ActionId.OmegaDiffuseWaveCannonAOE, unit.Placement, coneHalfAngle: MathF.PI / 3f))
        {
            Plugin.Log.Info($"Hit: {hit.Role} by Diffuse Wave Cannon ");
            hit.Die("Diffuse Wave Cannon");
        }
    }
    
    private void Run_Omega_4000A409_1()
    {
        SimEnemy? omega_4000A409_1 = null;
        SimEnemy? omega_4000A40A_1 = null;
        world.Events.Add(27.67f, () => omega_4000A409_1 = world.SpawnEnemy(new EnemySpawnConfig(BNpcBaseId: BNpcBaseId.OmegaHelper, NameId: BNpcNameId.OmegaFinal, Level: 1, Targetable: false, EnemyList: EnemyListMode.Never, IsVisible: false, Placement: new Placement(new Vector3(0.000f, -0.000f, 0.000f), -0.000f))));
        world.Events.Add(27.67f, () => omega_4000A40A_1 = world.SpawnEnemy(new EnemySpawnConfig(BNpcBaseId: BNpcBaseId.OmegaHelper, NameId: BNpcNameId.OmegaFinal, Level: 1, Targetable: false, EnemyList: EnemyListMode.Never, IsVisible: false, Placement: new Placement(new Vector3(0.000f, -0.000f, 0.000f), 3.140f))));
        world.Events.Add(41.74f, () =>
        {
            var targets = party.Find.OnSideN(new Placement(new(0, 0, 0), MathF.PI), state.MonitorSide.Mul, 2);
            if (targets.Count > 0)
                omega_4000A409_1?.Cast(ActionId.OversampledWaveCannonAoe, castSeconds: 0f, targetId: targets[0].GameObjectId);
            if (targets.Count > 1)
                omega_4000A40A_1?.Cast(ActionId.OversampledWaveCannonAoe, castSeconds: 0f, targetId: targets[1].GameObjectId);
            ResolveMonitors(targets);
        });
        
    }
    
    private void ResolveMonitors(IReadOnlyList<SimPartySlot> targets)
    {
        foreach (var target in targets)
        {
            Plugin.Log.Info($"Hit: {target.Role} by Monitor");
            if (topUtils.IsDamageLethal(target, ruin: true))
            {
                target.Die("Oversampled Wave Cannon");
            }
            else
            { 
                target.AddStatus(StatusId.MagicVulnerabilityUp, 4.960f);
                target.AddStatus(StatusId.TwiceComeRuin, 6.960f);
            }
        }
    }


    private void Run_Omega_F_4000A40B_2()
    {
        var firstLegs = state.OmegaAttacks[0] == OmegaAttack.Legs;
        var secondLegs = state.OmegaAttacks[2] == OmegaAttack.Legs;
        bool[] superliminalSteel = [firstLegs, firstLegs, secondLegs, secondLegs, false, false];
        uint[] superliminalActionIds = [ActionId.SuperliminalSteelOmenR, ActionId.SuperliminalSteelOmenL, ActionId.SuperliminalSteelOmenR, ActionId.SuperliminalSteelOmenL, 0, 0];
        Vector3[] superliminalTargets = [Geometry.SuperliminalSteelOmenTargetR, Geometry.SuperliminalSteelOmenTargetL, Geometry.SuperliminalSteelOmenTargetR, Geometry.SuperliminalSteelOmenTargetL, default, default];
        EightWayDirection[] superliminalDirections = [state.AttackDirections[0], state.AttackDirections[0], state.AttackDirections[3], state.AttackDirections[3], EightWayDirection.N, EightWayDirection.N];
        float[] superliminalOffset = [-4f, -4f, 0, 0, 0, 0];
        float[] dynamisOffsets = [0, 0, 1, 1, 2, 2, 3, 3];
        var nearHelper1 = topUtils.HelloWorld(state.HelloWorldTargets[0], true);
        var farHelper1 = topUtils.HelloWorld(state.HelloWorldTargets[1], false);
        var nearHelper2 = topUtils.HelloWorld(state.HelloWorldTargets[2], true);
        var farHelper2 = topUtils.HelloWorld(state.HelloWorldTargets[3], false);
                                
        for (int i = 0; i < 6; i++)
        {
            SimEnemy? omega_F_4000A40B_2 = null;
            var offset = superliminalOffset[i];
            var direction = superliminalDirections[i];
            var omenId = superliminalActionIds[i];
            var target = superliminalTargets[i];
            var helper1 = i % 2 == 0 ? nearHelper1 : farHelper1;
            var helper2 = i  % 2 == 0 ? nearHelper2 : farHelper2;
            var dynamisOffset = dynamisOffsets[i];
            
            world.Events.Add(26.92f + offset, () => omega_F_4000A40B_2 = world.SpawnEnemy(new EnemySpawnConfig(BNpcBaseId: BNpcBaseId.OmegaHelper, NameId: BNpcNameId.OmegaFDynamis, Level: 1, Targetable: false, EnemyList: EnemyListMode.Never, IsVisible: false, Placement: direction.Apply(Geometry.SuperliminalSteelOmenPlacement))));
            if (superliminalSteel[i])
                world.Events.Add(26.96f + offset, () => omega_F_4000A40B_2?.Cast(omenId, targetLocation: direction.Apply(target), omenDelay: Duration.OmegaAttackOmenDelay, castSeconds: 1.200f, targetId: omega_F_4000A40B_2?.GameObjectId));
            
            world.Events.Add(41.16f + dynamisOffset, () => helper1.SetPosition(omega_F_4000A40B_2));
            world.Events.Add(41.25f + dynamisOffset, () => helper1.CastSpell(omega_F_4000A40B_2));
            
            world.Events.Add(59.26f + dynamisOffset, () => helper2.SetPosition(omega_F_4000A40B_2));
            world.Events.Add(59.27f + dynamisOffset, () => helper2.CastSpell(omega_F_4000A40B_2));
        }
    }
}
