using System;
using System.Linq;
using System.Numerics;
using System.Reflection;
using System.Runtime.InteropServices;
using AnoMech.Pointers;
using Dalamud.Game.Addon.Lifecycle;
using Dalamud.Game.Addon.Lifecycle.AddonArgTypes;
using Dalamud.Game.ClientState.Conditions;
using Dalamud.Hooking;
using FFXIVClientStructs.FFXIV.Client.Game;
using FFXIVClientStructs.FFXIV.Client.Game.Character;
using FFXIVClientStructs.FFXIV.Client.Game.Event;
using FFXIVClientStructs.FFXIV.Client.Graphics.Environment;
using FFXIVClientStructs.FFXIV.Client.Network;
using FFXIVClientStructs.FFXIV.Client.UI.Agent;
using Lumina.Excel.Sheets;
using static FFXIVClientStructs.FFXIV.Client.Network.PacketDispatcher.Delegates;
using ThreadingTask = System.Threading.Tasks.Task;

namespace AnoMech.Core.Map;

// Client-side zone loading and packet firewall. Ported from Hyperborea (Memory.cs
// + Utils.cs). Must be in the Inn before calling Enter(); Leave() reloads the inn.
// All public methods must be called from the framework thread.
public sealed unsafe class ZoneSession : IDisposable
{
    // TerritoryIntendedUse.Inn = 2 (from ECommons TerritoryIntendedUseEnum)
    private const uint InnIntendedUse = 2;

    // ── Native delegates ──────────────────────────────────────────────────────

    private delegate byte SendPacketDelegate(nint a1, nint a2, nint a3, byte a4);
    private readonly Hook<SendPacketDelegate> sendPacketHook;

    // OnReceivePacket delegate type generated by FFXIVClientStructs from [VirtualFunction(1)]
    private readonly Hook<OnReceivePacket> receivePacketHook;

    // ── State ─────────────────────────────────────────────────────────────────

    private readonly ushort heartbeatOpcode;
    private uint? loadedInstanceContent;

    // Set true right before we open the Social window for a party resync; the Social
    // PostSetup listener closes it again and clears this. Distinguishes our open from
    // a manual one so manual opens aren't auto-closed.
    private bool autoCloseSocial;

    public bool IsActive { get; private set; }

    private uint savedTerritoryId;
    private Vector3 savedPosition;
    public float savedRotation;

    // ── Construction ──────────────────────────────────────────────────────────

    public ZoneSession()
    {
        // Heartbeat (ZoneUp) opcode — auto-detected by signature (from Hyperborea Memory.cs)
        heartbeatOpcode = (ushort)Marshal.ReadInt32(
            Plugin.SigScanner.ScanText("C7 44 24 ?? ?? ?? ?? ?? 48 F7 F1") + 0x4);
        Plugin.Log.Information($"[ZoneSession] Heartbeat opcode: {heartbeatOpcode}");

        // Send-packet hook (sig from Hyperborea Memory.cs)
        var sendAddr = Plugin.SigScanner.ScanText(
            "48 89 5C 24 ?? 48 89 74 24 ?? 4C 89 64 24 ?? 55 41 56 41 57 48 8B EC 48 83 EC 70");
        sendPacketHook = Plugin.GameInterop.HookFromAddress<SendPacketDelegate>(
            sendAddr, SendPacketDetour);

        // Receive-packet hook — address from PacketDispatcher.StaticVirtualTablePointer->OnReceivePacket.
        // This is the standard approach used by ECommons/Dalamud's GameNetwork service.
        // PacketDispatcher.Delegates.OnReceivePacket and StaticVirtualTablePointer are generated by
        // FFXIVClientStructs from [VirtualFunction(1)] + [VirtualTable] on PacketDispatcher.
        var receiveAddr = (nint)PacketDispatcher.StaticVirtualTablePointer->OnReceivePacket;
        Plugin.Log.Information($"[ZoneSession] OnReceivePacket: {receiveAddr:X}");
        receivePacketHook = Plugin.GameInterop.HookFromAddress<OnReceivePacket>(
            receiveAddr, ReceivePacketDetour);

        Plugin.AddonLifecycle.RegisterListener(AddonEvent.PostSetup, "Social", OnSocialPostSetup);

        Plugin.Log.Information("[ZoneSession] Initialized.");
    }

    // ── Public API ────────────────────────────────────────────────────────────

    public static bool IsInInn()
    {
        var row = Plugin.DataManager.GetExcelSheet<TerritoryType>()
            ?.GetRowOrDefault(Plugin.ClientState.TerritoryType);
        return row?.TerritoryIntendedUse.RowId == InnIntendedUse;
    }

    // Any state in which the local player can't freely act. Used as a second
    // gate before starting a scenario from an inn so we don't kick off mid-
    // cutscene, mid-NPC-event, mid-craft, mid-zone, etc.
    public static bool IsPlayerBusy()
    {
        var c = Plugin.Condition;
        return c[ConditionFlag.WatchingCutscene]
            || c[ConditionFlag.WatchingCutscene78]
            || c[ConditionFlag.OccupiedInCutSceneEvent]
            || c[ConditionFlag.OccupiedInEvent]
            || c[ConditionFlag.OccupiedInQuestEvent]
            || c[ConditionFlag.OccupiedSummoningBell]
            || c[ConditionFlag.Occupied30]
            || c[ConditionFlag.Occupied33]
            || c[ConditionFlag.Occupied38]
            || c[ConditionFlag.Occupied39]
            || c[ConditionFlag.Crafting]
            || c[ConditionFlag.ExecutingCraftingAction]
            || c[ConditionFlag.PreparingToCraft]
            || c[ConditionFlag.Gathering]
            || c[ConditionFlag.ExecutingGatheringAction]
            || c[ConditionFlag.Fishing]
            || c[ConditionFlag.TradeOpen]
            || c[ConditionFlag.BetweenAreas]
            || c[ConditionFlag.LoggingOut]
            || c[ConditionFlag.WaitingForDutyFinder]
            || c[ConditionFlag.InDutyQueue]
            || c[ConditionFlag.InCombat]
            || c[ConditionFlag.Mounted]
            || c[ConditionFlag.Jumping]
            || c[ConditionFlag.Occupied];
    }

    // Load the target territory, teleport player to playerSpawn, enable firewall.
    // Firewall is enabled before the zone load (matching Hyperborea's sequence).
    public void Enter(uint territoryId, Vector3 playerSpawn)
    {
        var localPlayer = Plugin.ObjectTable.LocalPlayer!;

        savedTerritoryId = Plugin.ClientState.TerritoryType;
        savedPosition = localPlayer.Position;
        savedRotation = localPlayer.Rotation;

        EnableFirewall();
        LoadZoneInternal(territoryId, false, playerSpawn);
        IsActive = true;
        Plugin.Log.Information($"[ZoneSession] Entered territory {territoryId}.");
    }

    // Immediately set the active weather. Must be called on the framework thread.
    // weatherId is a Weather-sheet row; transition is the fade time in seconds.
    public void SetWeather(byte weatherId, float transition = 0.5f)
    {
        var env = EnvManager.Instance();
        if (env == null) return;
        env->ActiveWeather = weatherId;
        env->TransitionTime = transition;
    }

    // Apply weather after a fresh zone load. Delayed 1 second so the engine finishes setup.
    public void ApplyWeather(byte weatherId)
        => ThreadingTask.Delay(1000).ContinueWith(_ => Plugin.Framework.Run(() => SetWeather(weatherId)));

    // Reload the saved inn territory and restore position; disable firewall.
    public void Revert()
    {
        // We need to wait before calling DisableFirewall(), so we'll set the Occupied condition to be sure the Player doesn't do anything in the meantime. 
        var condition = Conditions.Instance();
        condition->Occupied = true;

        if (savedTerritoryId != 0)
            LoadZoneInternal(savedTerritoryId, true, savedPosition, savedRotation);
        savedTerritoryId = 0;
        IsActive = false;
        Plugin.Log.Information("[ZoneSession] Reverted to inn.");

        // If this isn't delayed, a Packet will be sent to the server!!!
        ThreadingTask.Delay(1000).ContinueWith(_ =>
        {
            // The Player could do something like jump, so to be extremely sure we are where we are supposed to, we set the Position and Rotation again.
            SetLocalPlayerPosition(savedPosition, savedRotation);
            condition->Occupied = false;
            
            DisableFirewall();
        });

        // Resync the real party HUD once the inn reload has settled. A bare
        // InfoProxyPartyMember.RequestData() sends the same request the Social window
        // does but doesn't sync MainGroup — the HUD update is client-side work the
        // Social agent does on the reply (proven via packet trace). So open the Social
        // agent and let it do that work itself. (Closing it again is a follow-up step.)
        ThreadingTask.Delay(1500).ContinueWith(_ => Plugin.Framework.Run(OpenSocialForPartyResync));
    }

    // Opens the Social agent, which issues its own (callback-routed) party-member
    // request and processes the reply into the party HUD — the step a bare RequestData
    // can't trigger. Firing this from the settled inn state mirrors a manual open.
    private void OpenSocialForPartyResync()
    {
        var am = AgentModule.Instance();
        var social = am != null ? am->GetAgentByInternalId(AgentId.Social) : null;
        if (social == null) return;
        autoCloseSocial = true;
        social->Show();
        Plugin.Log.Information("[ZoneSession] Opened Social for party resync.");
    }

    // Closes the Social window again as soon as it finishes opening — but only when
    // we opened it (autoCloseSocial), so a manual open is left alone.
    private void OnSocialPostSetup(AddonEvent type, AddonArgs args)
    {
        if (!autoCloseSocial) return;
        autoCloseSocial = false;

        var am = AgentModule.Instance();
        var s = am != null ? am->GetAgentByInternalId(AgentId.Social) : null;
        if (s != null) s->Hide();
        Plugin.Log.Information("[ZoneSession] Auto-closed Social after party resync.");
    }

    public void EnableFirewall()
    {
        sendPacketHook.Enable();
        receivePacketHook.Enable();
    }

    public void DisableFirewall()
    {
        sendPacketHook.Disable();
        receivePacketHook.Disable();
    }

    // ── Zone loading sequence (mirrors Hyperborea Utils.LoadZone) ─────────────

    private void LoadZoneInternal(uint territory, bool unloading, Vector3 playerPos, float? rotation = null)
    {
        var eventFramework = EventFramework.Instance();
        var gm = GameMain.Instance();
        Plugin.Log.Information($"[ZoneSession] LoadZone territory={territory} ef={((nint)eventFramework):X} gm={((nint)gm):X}");
        if (eventFramework == null || gm == null)
        {
            Plugin.Log.Error("[ZoneSession] Null singleton — aborting zone load");
            return;
        }

        Plugin.Log.Information("[ZoneSession] Step 1: FinalizeInstanceContent");
        if (loadedInstanceContent != null)
        {
            EventFrameworkPointers.TerminateDirector(eventFramework, 0x80030000 + loadedInstanceContent.Value);
            loadedInstanceContent = null;
        }

        Plugin.Log.Information("[ZoneSession] Step 2: DisableDraw all objects");
        foreach (var obj in Plugin.ObjectTable)
        {
            if (obj.Address == IntPtr.Zero) continue;
            ((FFXIVClientStructs.FFXIV.Client.Game.Object.GameObject*)obj.Address)->DisableDraw();
        }

        Plugin.Log.Information("[ZoneSession] Step 3: InitDirector");
        var content = GetContentId(territory);
        Plugin.Log.Information($"[ZoneSession] ContentId={content}");
        if (content is { } cid && cid != 0)
        {
            EventFrameworkPointers.InitDirector(eventFramework, 0x80030000 + cid, cid, 0);

            if (!unloading)
            {
                loadedInstanceContent = cid;
            }
        }

        Plugin.Log.Information("[ZoneSession] Step 4: LoadZone (native)");
        GameMainPointers.LoadZone(gm, territory, 0, 0, 1);

        Plugin.Log.Information("[ZoneSession] Step 5: SetupTerritoryType");
        eventFramework->SetTerritoryTypeId((ushort)territory);

        Plugin.Log.Information("[ZoneSession] Step 6: SyncClientState");
        SyncClientStateTerritoryType((ushort)territory);

        Plugin.Log.Information("[ZoneSession] Step 7: SetPosition");
        SetLocalPlayerPosition(playerPos, rotation);

        Plugin.Log.Information("[ZoneSession] LoadZone complete");
    }

    private void SetLocalPlayerPosition(Vector3 position, float? rotation = null)
    {
        if (Plugin.ObjectTable.LocalPlayer is { Address: var addr } && addr != IntPtr.Zero)
        {
            var chara = (Character*)addr;
            chara->GameObject.SetPosition(position.X, position.Y, position.Z);

            if (rotation != null)
            {
                chara->GameObject.SetRotation(rotation.Value);
            }
        }
    }

    private static uint? GetContentId(uint territoryId)
    {
        var row = Plugin.DataManager.GetExcelSheet<TerritoryType>()?.GetRowOrDefault(territoryId);
        var cid = row?.ContentFinderCondition.ValueNullable?.Content.RowId;
        return cid is null or 0 ? null : cid;
    }

    private static void SyncClientStateTerritoryType(ushort territory)
    {
        try
        {
            var type = Plugin.ClientState.GetType();
            var prop = type.GetProperty("TerritoryType",
                BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance);
            if (prop?.CanWrite == true)
            {
                prop.SetValue(Plugin.ClientState, territory);
                return;
            }
            var field = type.GetField("territoryType",
                BindingFlags.NonPublic | BindingFlags.Instance)
                ?? type.GetField("TerritoryType",
                BindingFlags.NonPublic | BindingFlags.Instance);
            field?.SetValue(Plugin.ClientState, territory);
        }
        catch (Exception e)
        {
            Plugin.Log.Warning($"[ZoneSession] Could not sync ClientState.TerritoryType: {e.Message}");
        }
    }

    // ── Packet firewall detours (mirrored from Hyperborea Memory.cs) ──────────

    private byte SendPacketDetour(nint a1, nint a2, nint a3, byte a4)
    {
        const byte defaultReturn = 1;
        if (a2 == IntPtr.Zero) return defaultReturn;
        try
        {
            if (*(ushort*)a2 == heartbeatOpcode)
                return sendPacketHook.Original(a1, a2, a3, a4);
        }
        catch (Exception e)
        {
            Plugin.Log.Error($"[ZoneSession] SendPacketDetour: {e.Message}");
            return defaultReturn;
        }
        return defaultReturn;
    }

    private void ReceivePacketDetour(PacketDispatcher* a1, uint a2, nint a3)
    {
        if (a3 == IntPtr.Zero) return;
        try
        {
            // Release builds always run the firewall (safe mode hardcoded on).
            // Debug builds honour the config toggle so it can be flipped off
            // for testing without affecting shipped behaviour.
#if DEBUG
            var safeMode = Plugin.Config.SafeMode;
#else
            const bool safeMode = true;
#endif
            if (!safeMode || Plugin.Config.ZoneDownOpcodes.Contains(*(ushort*)(a3 + 2)))
                receivePacketHook.Original(a1, a2, a3);
        }
        catch (Exception e)
        {
            Plugin.Log.Error($"[ZoneSession] ReceivePacketDetour: {e.Message}");
        }
    }

    // ── Lifecycle ─────────────────────────────────────────────────────────────

    public void Dispose()
    {
        Plugin.AddonLifecycle.UnregisterListener(AddonEvent.PostSetup, "Social", OnSocialPostSetup);

        // To not freeze a player that's disabling/reloading/etc the plugin while not in a Scenario
        if (IsActive)
        {
            Revert();
        }

        DisableFirewall();
        sendPacketHook.Dispose();
        receivePacketHook.Dispose();
    }
}
