using System;
using System.Linq;
using System.Reflection;
using System.Runtime.InteropServices;
using System.Numerics;
using ThreadingTask = System.Threading.Tasks.Task;
using Dalamud.Hooking;
using FFXIVClientStructs.FFXIV.Client.Game;
using FFXIVClientStructs.FFXIV.Client.Game.Character;
using FFXIVClientStructs.FFXIV.Client.Game.Event;
using FFXIVClientStructs.FFXIV.Client.Graphics.Environment;
using FFXIVClientStructs.FFXIV.Client.Network;
using FFXIVClientStructs.FFXIV.Client.System.Framework;
using Lumina.Excel.Sheets;
using static FFXIVClientStructs.FFXIV.Client.Network.PacketDispatcher.Delegates;

namespace UltiSim.Core.Map;

// Client-side zone loading and packet firewall. Ported from Hyperborea (Memory.cs
// + Utils.cs). Must be in the Inn before calling Enter(); Leave() reloads the inn.
// All public methods must be called from the framework thread.
public sealed unsafe class ZoneSession : IDisposable
{
    // TerritoryIntendedUse.Inn = 2 (from ECommons TerritoryIntendedUseEnum)
    private const uint InnIntendedUse = 2;

    // ── Native delegates ──────────────────────────────────────────────────────

    private delegate nint LoadZoneDelegate(nint a1, uint territory, int a3, byte a4, byte a5, byte a6);
    private readonly LoadZoneDelegate loadZone;

    private delegate nint SetupTerritoryTypeDelegate(void* eventFramework, ushort territoryType);
    private readonly SetupTerritoryTypeDelegate setupTerritoryType;

    // Hooked at the call-site address (Hyperborea [EzHook("E8...", true)] pattern).
    // We never Enable() these — they exist only for their MinHook trampoline, which
    // correctly handles the E8 relative offset regardless of other plugin patches.
    private delegate nint SetupInstanceContentDelegate(nint a1, uint a2, uint a3, uint a4);
    private readonly Hook<SetupInstanceContentDelegate> setupInstanceContentHook;

    private delegate byte FinalizeInstanceContentDelegate(nint a1, uint a2);
    private readonly Hook<FinalizeInstanceContentDelegate> finalizeInstanceContentHook;

    private delegate byte SendPacketDelegate(nint a1, nint a2, nint a3, byte a4);
    private readonly Hook<SendPacketDelegate> sendPacketHook;

    // OnReceivePacket delegate type generated by FFXIVClientStructs from [VirtualFunction(1)]
    private readonly Hook<OnReceivePacket> receivePacketHook;

    // ── State ─────────────────────────────────────────────────────────────────

    private readonly ushort heartbeatOpcode;
    private uint? instanceContentWasLoaded;

    public bool IsActive { get; private set; }

    private uint savedTerritoryId;
    private Vector3 savedPosition;

    // ── Construction ──────────────────────────────────────────────────────────

    public ZoneSession()
    {
        // LoadZone native function (sig from Hyperborea Memory.cs)
        var loadZoneAddr = Plugin.SigScanner.ScanText(
            "40 55 56 41 54 41 56 41 57 48 81 EC ?? ?? ?? ?? 48 8B 05 ?? ?? ?? ?? 48 33 C4 48 89 44 24");
        loadZone = Marshal.GetDelegateForFunctionPointer<LoadZoneDelegate>(loadZoneAddr);

        // SetupTerritoryType native function (sig from Hyperborea Memory.cs)
        var setupTTAddr = Plugin.SigScanner.ScanText(
            "48 89 5C 24 ?? 48 89 7C 24 ?? 41 56 48 83 EC ?? 48 8B D9 48 89 6C 24");
        setupTerritoryType = Marshal.GetDelegateForFunctionPointer<SetupTerritoryTypeDelegate>(setupTTAddr);

        // SetupInstanceContent — hooked AT the call site, not at the function entry.
        // Mirrors Hyperborea's [EzHook("E8...", true)] pattern exactly. The hook is
        // never enabled; we call .Original(...) so MinHook's trampoline executes the
        // original E8 relative call with the correct offset for its trampoline location.
        var setupCallSite = Plugin.SigScanner.ScanText(
            "E8 ?? ?? ?? ?? E9 ?? ?? ?? ?? E8 ?? ?? ?? ?? 8B 54 24 70 48 8B C8 E8 ?? ?? ?? ?? E9 ?? ?? ?? ?? E8 ?? ?? ?? ?? 0F B6 54 24");
        setupInstanceContentHook = Plugin.GameInterop.HookFromAddress<SetupInstanceContentDelegate>(
            setupCallSite, (a1, a2, a3, a4) => 0);   // detour never fires — hook stays disabled

        // FinalizeInstanceContent — direct function-entry sig (starts with MOV prologue, not E8).
        // Hooked for consistency so .Original() also goes through the trampoline correctly.
        var finalizeAddr = Plugin.SigScanner.ScanText(
            "48 89 5C 24 ?? 48 89 6C 24 ?? 48 89 74 24 ?? 57 48 83 EC 70 48 8D B1");
        finalizeInstanceContentHook = Plugin.GameInterop.HookFromAddress<FinalizeInstanceContentDelegate>(
            finalizeAddr, (a1, a2) => 0);              // detour never fires — hook stays disabled

        // Heartbeat (ZoneUp) opcode — auto-detected by signature (from Hyperborea Memory.cs)
        heartbeatOpcode = (ushort)Marshal.ReadInt32(
            Plugin.SigScanner.ScanText("C7 44 24 ?? ?? ?? ?? ?? 48 F7 F1") + 0x4);
        Plugin.Log.Information($"[ZoneSession] Heartbeat opcode: {heartbeatOpcode}");

        // Send-packet hook (sig from Hyperborea Memory.cs)
        var sendAddr = Plugin.SigScanner.ScanText(
            "48 89 5C 24 ?? 48 89 74 24 ?? 4C 89 64 24 ?? 55 41 56 41 57 48 8B EC 48 83 EC 70");
        sendPacketHook = Plugin.GameInterop.HookFromAddress<SendPacketDelegate>(
            sendAddr, SendPacketDetour);

        // Receive-packet hook — address from PacketDispatcher.StaticVirtualTablePointer->OnReceivePacket.
        // This is the standard approach used by ECommons/Dalamud's GameNetwork service.
        // PacketDispatcher.Delegates.OnReceivePacket and StaticVirtualTablePointer are generated by
        // FFXIVClientStructs from [VirtualFunction(1)] + [VirtualTable] on PacketDispatcher.
        var receiveAddr = (nint)PacketDispatcher.StaticVirtualTablePointer->OnReceivePacket;
        Plugin.Log.Information($"[ZoneSession] OnReceivePacket: {receiveAddr:X}");
        receivePacketHook = Plugin.GameInterop.HookFromAddress<OnReceivePacket>(
            receiveAddr, ReceivePacketDetour);

        Plugin.Log.Information("[ZoneSession] Initialized.");
    }

    // ── Public API ────────────────────────────────────────────────────────────

    public static bool IsInInn()
    {
        var row = Plugin.DataManager.GetExcelSheet<TerritoryType>()
            ?.GetRowOrDefault(Plugin.ClientState.TerritoryType);
        return row?.TerritoryIntendedUse.RowId == InnIntendedUse;
    }

    // Load the target territory, teleport player to playerSpawn, enable firewall.
    // Firewall is enabled before the zone load (matching Hyperborea's sequence).
    public void Enter(uint territoryId, Vector3 playerSpawn)
    {
        savedTerritoryId = Plugin.ClientState.TerritoryType;
        savedPosition = Plugin.ObjectTable.LocalPlayer!.Position;

        EnableFirewall();
        LoadZoneInternal(territoryId, playerSpawn);
        IsActive = true;
        Plugin.Log.Information($"[ZoneSession] Entered territory {territoryId}.");
    }

    // Apply weather after zone loads. Delayed 1 second so the engine finishes setup.
    public void ApplyWeather(byte weatherId)
    {
        ThreadingTask.Delay(1000).ContinueWith(_ => Plugin.Framework.Run(() =>
        {
            var env = EnvManager.Instance();
            env->ActiveWeather = weatherId;
            env->TransitionTime = 0.5f;
        }));
    }

    // Reload the saved inn territory and restore position; disable firewall.
    public void Revert()
    {
        DisableFirewall();
        if (savedTerritoryId != 0)
            LoadZoneInternal(savedTerritoryId, savedPosition);
        savedTerritoryId = 0;
        IsActive = false;
        Plugin.Log.Information("[ZoneSession] Reverted to inn.");
    }

    public void EnableFirewall()
    {
        sendPacketHook.Enable();
        receivePacketHook.Enable();
    }

    public void DisableFirewall()
    {
        sendPacketHook.Disable();
        receivePacketHook.Disable();
    }

    // ── Zone loading sequence (mirrors Hyperborea Utils.LoadZone) ─────────────

    private void LoadZoneInternal(uint territory, Vector3 playerPos)
    {
        var ef = EventFramework.Instance();
        var gm = GameMain.Instance();
        Plugin.Log.Information($"[ZoneSession] LoadZone territory={territory} ef={((nint)ef):X} gm={((nint)gm):X}");
        if (ef == null || gm == null)
        {
            Plugin.Log.Error("[ZoneSession] Null singleton — aborting zone load");
            return;
        }

        Plugin.Log.Information("[ZoneSession] Step 1: FinalizeInstanceContent");
        if (instanceContentWasLoaded != null)
        {
            finalizeInstanceContentHook.Original((nint)ef, 0x80030000 + instanceContentWasLoaded.Value);
            instanceContentWasLoaded = null;
        }

        Plugin.Log.Information("[ZoneSession] Step 2: DisableDraw all objects");
        foreach (var obj in Plugin.ObjectTable)
        {
            if (obj.Address == IntPtr.Zero) continue;
            ((FFXIVClientStructs.FFXIV.Client.Game.Object.GameObject*)obj.Address)->DisableDraw();
        }

        Plugin.Log.Information("[ZoneSession] Step 3: SetupInstanceContent");
        var content = GetContentId(territory);
        Plugin.Log.Information($"[ZoneSession] ContentId={content}");
        if (content is { } cid && cid != 0)
        {
            setupInstanceContentHook.Original((nint)ef, 0x80030000 + cid, cid, 0);
            instanceContentWasLoaded = cid;
        }

        Plugin.Log.Information("[ZoneSession] Step 4: LoadZone (native)");
        loadZone((nint)gm, territory, 0, 0, 1, 1);

        Plugin.Log.Information("[ZoneSession] Step 5: SetupTerritoryType");
        setupTerritoryType(ef, (ushort)territory);

        Plugin.Log.Information("[ZoneSession] Step 6: SyncClientState");
        SyncClientStateTerritoryType((ushort)territory);

        Plugin.Log.Information("[ZoneSession] Step 7: SetPosition");
        if (Plugin.ObjectTable.LocalPlayer is { Address: var addr } && addr != IntPtr.Zero)
        {
            var chara = (Character*)addr;
            chara->GameObject.SetPosition(playerPos.X, playerPos.Y, playerPos.Z);
        }
        Plugin.Log.Information("[ZoneSession] LoadZone complete");
    }

    private static uint? GetContentId(uint territoryId)
    {
        var row = Plugin.DataManager.GetExcelSheet<TerritoryType>()?.GetRowOrDefault(territoryId);
        var cid = row?.ContentFinderCondition.ValueNullable?.Content.RowId;
        return cid is null or 0 ? null : cid;
    }

    private static void SyncClientStateTerritoryType(ushort territory)
    {
        try
        {
            var type = Plugin.ClientState.GetType();
            var prop = type.GetProperty("TerritoryType",
                BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance);
            if (prop?.CanWrite == true)
            {
                prop.SetValue(Plugin.ClientState, territory);
                return;
            }
            var field = type.GetField("territoryType",
                BindingFlags.NonPublic | BindingFlags.Instance)
                ?? type.GetField("TerritoryType",
                BindingFlags.NonPublic | BindingFlags.Instance);
            field?.SetValue(Plugin.ClientState, territory);
        }
        catch (Exception e)
        {
            Plugin.Log.Warning($"[ZoneSession] Could not sync ClientState.TerritoryType: {e.Message}");
        }
    }

    // ── Packet firewall detours (mirrored from Hyperborea Memory.cs) ──────────

    private byte SendPacketDetour(nint a1, nint a2, nint a3, byte a4)
    {
        const byte defaultReturn = 1;
        if (a2 == IntPtr.Zero) return defaultReturn;
        try
        {
            if (*(ushort*)a2 == heartbeatOpcode)
                return sendPacketHook.Original(a1, a2, a3, a4);
        }
        catch (Exception e)
        {
            Plugin.Log.Error($"[ZoneSession] SendPacketDetour: {e.Message}");
            return defaultReturn;
        }
        return defaultReturn;
    }

    private void ReceivePacketDetour(PacketDispatcher* a1, uint a2, nint a3)
    {
        if (a3 == IntPtr.Zero) return;
        try
        {
            var opcode = *(ushort*)(a3 + 2);
            if (Plugin.Config.ZoneDownOpcodes.Contains(opcode))
                receivePacketHook.Original(a1, a2, a3);
        }
        catch (Exception e)
        {
            Plugin.Log.Error($"[ZoneSession] ReceivePacketDetour: {e.Message}");
        }
    }

    // ── Lifecycle ─────────────────────────────────────────────────────────────

    public void Dispose()
    {
        Revert();
        sendPacketHook.Dispose();
        receivePacketHook.Dispose();
        setupInstanceContentHook.Dispose();
        finalizeInstanceContentHook.Dispose();
    }
}
